name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: shining-env-446009-p3
  REGION: asia-northeast3
  SERVICE_NAME: newsletter
  PORT: 8080

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authorize Docker push
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Build and Push Container
      run: |-
        docker build -t asia-northeast3-docker.pkg.dev/${{ env.PROJECT_ID }}/newsletter/newsletter:${{ github.sha }} .
        docker push asia-northeast3-docker.pkg.dev/${{ env.PROJECT_ID }}/newsletter/newsletter:${{ github.sha }}

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: asia-northeast3-docker.pkg.dev/${{ env.PROJECT_ID }}/newsletter/newsletter:${{ github.sha }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
